name: Build SA-MP Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar source
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK, NDK e CMake
        run: |
          yes | sdkmanager --licenses >/dev/null || true
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0" "ndk;28.0.13004108" "cmake;3.22.1"

      - name: Permissão Gradle
        run: chmod +x gradlew

      - name: Compilar APK
        run: ./gradlew assembleVer_releaseDebug --stacktrace

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: SAMP-NoobCoder-APK
          path: app/build/outputs/apk/**/*.apk
